### ISSUE TITLE
Fix CLI login by loading a service account in Google Developers Console

### ISSUE THREAD

**Issue by sih4sing5hong5** [sih4sing5hong5/google-sites-liberation#119]
If anyone is interesting in fixing this function, you can look at [Using Signed Credentials](http://gspread.readthedocs.org/en/latest/oauth2.html#using-signed-credentials).

Once you get the `json` containing a key and an email account, you can load it and login without getting token every time.

**Comment by Firefishy** [comment]
Any chance you would be willing to accept a modest US$50 donation to get the CLI login working again? Paypal or similar.

**Comment by sih4sing5hong5** [comment]
Sorry, I know how to do but I have no time to maintain it.

You can ask @bestplay9384, he forked this project and did some good.


PS: 
I did public projects about language learning for my mother tongue recently. XD

**Comment by samyElaiassi** [comment]
I currently have a working fix, i'll make a pull request later on today
