### ISSUE TITLE
How to export contents form google sites of google apps? 

### ISSUE THREAD

**Issue by HuJK** [sih4sing5hong5/google-sites-liberation#120]
How to export contents form google sites of google apps? 
like this
https://sites.google.com/a/st.thsh.tp.edu.tw/xxxxxxxx/

**Comment by HuJK** [comment]
Ok,I found the method to export form google sites of google apps.
http://i.imgur.com/M06fKRb.png

**Comment by sih4sing5hong5** [comment]
May I use this image in README for #117 ?

Or you can add it in `img` directory by a new pull request if you want.

**Comment by HuJK** [comment]
No problem
